export const CATEGORY_KEYWORDS = {
  politics: [
    // English
    "government",
    "minister",
    "election",
    "parliament",
    "politics",
    "leader",
    "democracy",
    "bill",
    "law",
    "state",
    "party",
    "vote",
    "campaign",
    "assembly",
    // Telugu
    "ప్రభుత్వం",
    "మంత్రి",
    "ఎన్నికలు",
    "పార్లమెంట్",
    "రాజకీయాలు",
    "నాయకుడు",
    "ప్రజాస్వామ్యం",
    "బిల్లు",
    "చట్టం",
    "రాష్ట్రం",
    "పార్టీ",
    "ఓటు",
    "ప్రచారం",
    "అసెంబ్లీ",
  ],
  business: [
    // English
    "business",
    "market",
    "stock",
    "finance",
    "economy",
    "company",
    "industry",
    "investment",
    "trade",
    "growth",
    "sensex",
    "nifty",
    "shares",
    "rupee",
    "dollar",
    // Telugu
    "వ్యాపారం",
    "మార్కెట్",
    "స్టాక్",
    "ఆర్థిక",
    "ఆర్థిక వ్యవస్థ",
    "కంపెనీ",
    "పరిశ్రమ",
    "పెట్టుబడి",
    "వాణిజ్యం",
    "వృద్ధి",
    "సెన్సెక్స్",
    "నిఫ్టీ",
    "షేర్లు",
    "రూపాయి",
    "డాలర్",
  ],
  sports: [
  // --- Cricket Keywords (English) ---
  "cricket",
  "bat",
  "ball",
  "wicket",
  "bowler",
  "batsman",
  "all-rounder",
  "umpire",
  "run",
  "six",
  "four",
  "over",
  "innings",
  "stadium",
  "test match",
  "one day international",
  "T20",
  "IPL",
  "world cup",
  "boundary",
  "no ball",
  "wide ball",
  "catch",
  "fielding",
  "partnership",
  "century",
  "half-century",
  "duck",
  "maiden over",

  // --- Cricket Keywords (Telugu) ---
  "క్రికెట్",
  "బ్యాట్",
  "బంతి",
  "వికెట్",
  "బౌలర్",
  "బ్యాట్స్‌మన్",
  "ఆల్‌రౌండర్",
  "అంపైర్",
  "రన్",
  "సిక్స్",
  "ఫోర్",
  "ఓవర్",
  "ఇన్నింగ్స్",
  "స్టేడియం",
  "టెస్ట్ మ్యాచ్",
  "ఒకరోజు అంతర్జాతీయ",
  "టీ20",
  "ఐపీఎల్",
  "వరల్డ్ కప్",
  "బౌండరీ",
  "నో బాల్",
  "వైడ్ బాల్",
  "క్యాచ్",
  "ఫీల్డింగ్",
  "పార్ట్నర్‌షిప్",
  "సెంచరీ",
  "హాఫ్ సెంచరీ",
  "డక్",
  "మెయిడెన్ ఓవర్",

  // --- Indian Cricketers ---
  "Sachin Tendulkar", "సచిన్ టెండూల్కర్",
  "Virat Kohli", "విరాట్ కోహ్లీ",
  "Rohit Sharma", "రోహిత్ శర్మ",
  "MS Dhoni", "ఎంఎస్ ధోని",
  "Rahul Dravid", "రాహుల్ ద్రావిడ్",
  "Sourav Ganguly", "సౌరవ్ గంగూలీ",
  "Kapil Dev", "కపిల్ దేవ్",
  "Anil Kumble", "అనిల్ కుంబ్లే",
  "Yuvraj Singh", "యువరాజ్ సింగ్",
  "Hardik Pandya", "హార్దిక్ పాండ్యా",
  "Jasprit Bumrah", "జస్ప్రీత్ బుమ్రా",
  "Ravindra Jadeja", "రవీంద్ర జడేజా",
  "KL Rahul", "కేఎల్ రాహుల్",
  "Shikhar Dhawan", "శిఖర్ ధవన్",
  "Rishabh Pant", "రిషభ్ పంత్",
  "Mohammed Shami", "మొహమ్మద్ షమీ",
  "Bhuvneshwar Kumar", "భువనేశ్వర్ కుమార్",
  "Kuldeep Yadav", "కుల్దీప్ యాదవ్",
  "Sunil Gavaskar", "సునీల్ గవాస్కర్",
  "VVS Laxman", "వీవీఎస్ లక్ష్మణ్",

  // --- International Cricketers ---
  "Ricky Ponting", "రికీ పాంటింగ్",
  "Steve Smith", "స్టీవ్ స్మిత్",
  "Shane Warne", "షేన్ వార్న్",
  "Glenn McGrath", "గ్లెన్ మెక్‌గ్రాత్",
  "Adam Gilchrist", "ఆడమ్ గిల్‌క్రిస్ట్",
  "Brian Lara", "బ్రియాన్ లారా",
  "Chris Gayle", "క్రిస్ గేల్",
  "AB de Villiers", "ఏబీ డి విలియర్స్",
  "Jacques Kallis", "జాక్వస్ కాలిస్",
  "Kumar Sangakkara", "కుమార్ సంగక్కర",
  "Mahela Jayawardene", "మాహెల జయవర్ధనే",
  "Muttiah Muralitharan", "ముత్తయ్య మురళీధరన్",
  "Sanath Jayasuriya", "సనత్ జయసూర్య",
  "Wasim Akram", "వసీం అక్రమ్",
  "Waqar Younis", "వకార్ యూనిస్",
  "Shahid Afridi", "షాహిద్ అఫ్రిది",
  "Imran Khan", "ఇమ్రాన్ ఖాన్",
  "Babar Azam", "బాబర్ ఆజమ్",
  "Shaheen Afridi", "షాహీన్ అఫ్రిది",
  "Ben Stokes", "బెన్ స్టోక్స్",
  "Joe Root", "జో రూట్",
  "James Anderson", "జేమ్స్ ఆండర్సన్",
  "Stuart Broad", "స్టువర్ట్ బ్రాడ్",
  "Kane Williamson", "కేన్ విలియంసన్",
  "Martin Guptill", "మార్టిన్ గప్టిల్",
  "Trent Boult", "ట్రెంట్ బౌల్ట్",
  "Brendon McCullum", "బ్రెండన్ మెక్‌కల్లమ్"
],
  technology: [
    // English
    "tech",
    "AI",
    "software",
    "app",
    "startup",
    "technology",
    "internet",
    "data",
    "device",
    "cloud",
    "gadget",
    "innovation",
    "digital",
    "phone",
    "laptop",
    // Telugu
    "టెక్",
    "ఏఐ",
    "సాఫ్ట్‌వేర్",
    "యాప్",
    "స్టార్టప్",
    "సాంకేతికత",
    "ఇంటర్నెట్",
    "డేటా",
    "పరికరం",
    "క్లౌడ్",
    "గాడ్జెట్",
    "ఆవిష్కరణ",
    "డిజిటల్",
    "ఫోన్",
  ],
  crime: [
    // English
    "crime",
    "police",
    "arrest",
    "theft",
    "investigation",
    "case",
    "court",
    "accused",
    "suspect",
    "murder",
    "robbery",
    "fraud",
    "jailed",
    // Telugu
    "నేరం",
    "పోలీస్",
    "అరెస్ట్",
    "దొంగతనం",
    "విచారణ",
    "కేసు",
    "కోర్టు",
    "నిందితుడు",
    "హత్య",
    "దోపిడీ",
    "మోసం",
    "జైలు",
  ],
  entertainment: [
    // --- General & Industry Terms ---
    "entertainment",
    "cinema",
    "movie",
    "film",
    "review",
    "release",
    "box office",
    "celebrity",
    "hollywood",
    "bollywood",
    "tollywood",
    "kollywood",
    "mollywood",
    "sandalwood",
    "bigboss",
    "vivek agnihothri",
    "ss rajamouli",

    // --- Indian Actors & Actresses (English & Telugu) ---
    // Tollywood
    "chiranjeevi",
    "చిరంజీవి",
    "balakrishna",
    "బాలకృష్ణ",
    "nagarjuna",
    "నాగార్జున",
    "venkatesh",
    "వెంకటేష్",
    "pawan kalyan",
    "పవన్ కళ్యాణ్",
    "mahesh babu",
    "మహేష్ బాబు",
    "prabhas",
    "ప్రభాస్",
    "allu arjun",
    "అల్లు అర్జున్",
    "jr. ntr",
    "జూ. ఎన్టీఆర్",
    "ram charan",
    "రామ్ చరణ్",
    "vijay devarakonda",
    "విజయ్ దేవరకొండ",
    "nani",
    "నాని",
    "samantha",
    "సమంత",
    "anushka shetty",
    "అనుష్క శెట్టి",
    "rashmika mandanna",
    "రష్మిక మందన్న",
    "pooja hegde",
    "పూజా హెగ్డే",

    // Bollywood
    "shah rukh khan",
    "షారుఖ్ ఖాన్",
    "salman khan",
    "సల్మాన్ ఖాన్",
    "aamir khan",
    "అమీర్ ఖాన్",
    "amitabh bachchan",
    "అమితాబ్ బచ్చన్",
    "akshay kumar",
    "అక్షయ్ కుమార్",
    "ranbir kapoor",
    "రణబీర్ కపూర్",
    "deepika padukone",
    "దీపికా పదుకొనే",
    "alia bhatt",
    "అలియా భట్",
    "priyanka chopra",
    "ప్రియాంక చోప్రా",

    // Kollywood
    "rajinikanth",
    "రజనీకాంత్",
    "kamal haasan",
    "కమల్ హాసన్",
    "vijay",
    "విజయ్",
    "ajith kumar",
    "అజిత్ కుమార్",
    "suriya",
    "సూర్య",
    "dhanush",
    "ధనుష్",
    "vijay sethupathi",
    "విజయ్ సేతుపతి",

    // Mollywood
    "mohanlal",
    "మోహన్ లాల్",
    "mammootty",
    "మమ్ముట్టి",
    "fahadh faasil",
    "ఫహద్ ఫాసిల్",
    "dulquer salmaan",
    "దుల్కర్ సల్మాన్",

    // --- International Actors & Actresses ---
    "tom cruise",
    "leonardo dicaprio",
    "dwayne johnson",
    "the rock",
    "robert downey jr.",
    "brad pitt",
    "will smith",
    "tom hanks",
    "scarlett johansson",
    "angelina jolie",
    "jennifer lawrence",
    "meryl streep",
    "chris hemsworth",
    "chris evans",
    "zendaya",
    "margot robbie",
    "cillian murphy",

    // --- Web Series & Streaming ---
    "web series",
    "streaming",
    "ott",
    "netflix",
    "amazon prime",
    "disney+",
    "hotstar",
    "aha",
    "zee5",
    "series",
    "episode",
    "season",
  ],
  international: [
    // --- General Terms ---
    "world",
    "international",
    "global",
    "summit",
    "treaty",
    "war",
    "conflict",
    "diplomacy",
    "foreign policy",
    "united nations",
    "un",
    "ప్రపంచ",
    "అంతర్జాతీయ",
    "గ్లోబల్",
    "సమ్మిట్",
    "ఒప్పందం",
    "యుద్ధం",
    "సంఘర్షణ",
    "దౌత్యం",
    "విదేశాంగ విధానం",
    "ఐక్యరాజ్యసమితి",

    // --- Major Countries ---
    "america",
    "usa",
    "united states",
    "అమెరికా",
    "చైనా",
    "china",
    "russia",
    "రష్యా",
    "uk",
    "united kingdom",
    "బ్రిటన్",
    "japan",
    "జపాన్",
    "germany",
    "జర్మనీ",
    "france",
    "ఫ్రాన్స్",
    "canada",
    "కెనడా",
    "australia",
    "ఆస్ట్రేలియా",
    "pakistan",
    "పాకిస్తాన్",
    "sri lanka",
    "శ్రీలంక",
    "bangladesh",
    "బంగ్లాదేశ్",
    "ukraine",
    "ఉక్రెయిన్",
    "israel",
    "ఇజ్రాయెల్",
    "palestine",
    "పాలస్తీనా",

    // --- Major Cities ---
    "washington",
    "వాషింగ్టన్",
    "new york",
    "న్యూయార్క్",
    "beijing",
    "బీజింగ్",
    "moscow",
    "మాస్కో",
    "london",
    "లండన్",
    "tokyo",
    "టోక్యో",
    "paris",
    "పారిస్",
    "dubai",
    "దుబాయ్",
    "islamabad",
    "ఇస్లామాబాద్",
    "colombo",
    "కొలంబో",
    "dhaka",
    "ఢాకా",
    "kyiv",
    "కీవ్",
  ],
  astrology: [
    // English
    "horoscope",
    "astrology",
    "zodiac",
    "aries",
    "taurus",
    "gemini",
    "cancer",
    "leo",
    "virgo",
    "libra",
    "scorpio",
    "sagittarius",
    "capricorn",
    "aquarius",
    "pisces",
    "prediction",
    // Telugu
    "రాశి ఫలాలు",
    "జ్యోతిష్యం",
    "రాశి",
    "మేషం",
    "వృషభం",
    "మిథునం",
    "కర్కాటకం",
    "సింహం",
    "కన్య",
    "తుల",
    "వృశ్చికం",
    "ధనుస్సు",
    "మకరం",
    "కుంభం",
    "మీనం",
    "జాతకం",
  ],
  accidents: [
    // English
    "accident",
    "crash",
    "disaster",
    "dead",
    "injured",
    "collision",
    "tragedy",
    "emergency",
    "plane crash",
    "train crash",
    // Telugu
    "ప్రమాదం",
    "క్రాష్",
    "విపత్తు",
    "మృతి",
    "గాయపడ్డారు",
    "ఢీ",
    "విషాదం",
    "అత్యవసరం",
    "విమాన ప్రమాదం",
    "రైలు ప్రమాదం",
  ],
  andhra_pradesh: [
    "andhra pradesh",
    "ఆంధ్ర ప్రదేశ్",
    "amaravati",
    "అమరావతి",
    "srikakulam",
    "శ్రీకాకుళం",
    "vizianagaram",
    "విజయనగరం",
    "parvathipuram manyam",
    "పార్వతీపురం మన్యం",
    "alluri sitharama raju",
    "అల్లూరి సీతారామరాజు",
    "visakhapatnam",
    "విశాఖపట్నం",
    "విశాఖ",
    "anakapalli",
    "అనకాపల్లి",
    "kakinada",
    "కాకినాడ",
    "dr. b.r. ambedkar konaseema",
    "డా. బి.ఆర్. అంబేద్కర్ కోనసీమ",
    "east godavari",
    "తూర్పు గోదావరి",
    "west godavari",
    "పశ్చిమ గోదావరి",
    "eluru",
    "ఏలూరు",
    "krishna",
    "కృష్ణా",
    "ntr",
    "ఎన్టీఆర్",
    "guntur",
    "గుంటూరు",
    "palnadu",
    "పల్నాడు",
    "bapatla",
    "బాపట్ల",
    "prakasam",
    "ప్రకాశం",
    "sri potti sriramulu nellore",
    "శ్రీ పొట్టి శ్రీరాములు నెల్లూరు",
    "kurnool",
    "కర్నూలు",
    "nandyal",
    "నంద్యాల",
    "anantapur",
    "అనంతపురం",
    "sri sathya sai",
    "శ్రీ సత్యసాయి",
    "ysr kadapa",
    "వైఎస్ఆర్ కడప",
    "annamayya",
    "అన్నమయ్య",
    "tirupati",
    "తిరుపతి",
    "chittoor",
    "చిత్తూరు",
     // --- Political Leaders (AP) ---
    "ys jagan mohan reddy", "వైఎస్ జగన్ మోహన్ రెడ్డి",
    "n chandrababu naidu", "ఎన్ చంద్రబాబు నాయుడు",
    "ys rajasekhara reddy", "వైఎస్ రాజశేఖర రెడ్డి",
    "pawan kalyan", "పవన్ కళ్యాణ్",
    "ntr", "ఎన్టీఆర్", "jr ntr", "జూనియర్ ఎన్టీఆర్",
    "y s sharmila", "వైఎస్ షర్మిల",
    "botcha satyanarayana", "బొత్స సత్యనారాయణ",
    "yanamala ramakrishnudu", "యనమల రామకృష్ణుడు",
    "devineni uma", "దేవినేని ఉమ",
    "paritala ravi", "పరితాల రవి",
    "chandramohan reddy", "చంద్రమోహన్ రెడ్డి",
    "ganta srinivasa rao", "గంటా శ్రీనివాసరావు",
    "amaravati", "అమరావతి",
  ],
  telangana: [
    "telangana",
    "తెలంగాణ",
    "hyderabad",
    "హైదరాబాద్",
    "adilabad",
    "ఆదిలాబాద్",
    "bhadradri kothagudem",
    "భద్రాద్రి కొత్తగూడెం",
    "jagtial",
    "జగిత్యాల",
    "jangaon",
    "జనగాం",
    "jayashankar bhupalpally",
    "జయశంకర్ భూపాలపల్లి",
    "jogulamba gadwal",
    "జోగులాంబ గద్వాల",
    "kamareddy",
    "కామారెడ్డి",
    "karimnagar",
    "కరీంనగర్",
    "khammam",
    "ఖమ్మం",
    "komaram bheem",
    "కొమరం భీం",
    "mahabubabad",
    "మహబూబాబాద్",
    "mahabubnagar",
    "మహబూబ్‌నగర్",
    "mancherial",
    "మంచిర్యాల",
    "medak",
    "మెదక్",
    "medchal-malkajgiri",
    "మేడ్చల్-మల్కాజ్‌గిరి",
    "mulugu",
    "ములుగు",
    "nagarkurnool",
    "నాగర్‌కర్నూల్",
    "nalgonda",
    "నల్గొండ",
    "narayanpet",
    "నారాయణపేట",
    "nirmal",
    "నిర్మల్",
    "nizamabad",
    "నిజామాబాద్",
    "peddapalli",
    "పెద్దపల్లి",
    "rajanna sircilla",
    "రాజన్న సిరిసిల్ల",
    "rangareddy",
    "రంగారెడ్డి",
    "sangareddy",
    "సంగారెడ్డి",
    "siddipet",
    "సిద్దిపేట",
    "suryapet",
    "సూర్యాపేట",
    "vikarabad",
    "వికారాబాద్",
    "wanaparthy",
    "వనపర్తి",
    "warangal",
    "వరంగల్",
    "yadadri bhuvanagiri",
    "యాదాద్రి భువనగిరి",
    // --- Political Leaders (TS) ---
    "kcr", "కేసీఆర్",
    "k chandrashekar rao", "కల్వకుంట్ల చంద్రశేఖరరావు",
    "k t rama rao", "కేటీఆర్", "కె టి రామారావు",
    "harish rao", "హరీష్ రావు",
    "revanth reddy", "రేవంత్ రెడ్డి",
    "asaddudin owaisi", "అసదుద్దీన్ ఒవైసీ",
    "akbaruddin owaisi", "అక్బరుద్దీన్ ఒవైసీ",
    "jana reddy", "జనా రెడ్డి",
    "komatireddy venkat reddy", "కొమటిరెడ్డి వెంకట్ రెడ్డి",
    "etela rajender", "ఈటల రాజేందర్",
    "sabitha indra reddy", "సబితా ఇంద్రారెడ్డి",
    "pocharam srinivas reddy", "పోచారం శ్రీనివాస్ రెడ్డి",
    "tummala nageswara rao", "తుమ్మల నాగేశ్వరరావు",
    "kadiyam srihari", "కడియం శ్రీహరి",
  ],
  national: [
    // --- States (General) ---
    "Mohali",
    "arunachal pradesh",
    "అరుణాచల్ ప్రదేశ్",
    "itanagar",
    "ఇటానగర్",
    "assam",
    "అస్సాం",
    "dispur",
    "దిస్పూర్",
    "bihar",
    "బీహార్",
    "patna",
    "పాట్నా",
    "chhattisgarh",
    "ఛత్తీస్‌గఢ్",
    "raipur",
    "రాయ్‌పూర్",
    "goa",
    "గోవా",
    "panaji",
    "పనాజీ",
    "gujarat",
    "గుజరాత్",
    "gandhinagar",
    "గాంధీనగర్",
    "haryana",
    "హర్యానా",
    "chandigarh",
    "చండీగఢ్",
    "himachal pradesh",
    "హిమాచల్ ప్రదేశ్",
    "shimla",
    "సిమ్లా",
    "jharkhand",
    "జార్ఖండ్",
    "ranchi",
    "రాంచీ",
    "karnataka",
    "కర్ణాటక",
    "bengaluru",
    "బెంగళూరు",
    "kerala",
    "కేరళ",
    "thiruvananthapuram",
    "తిరువనంతపురం",
    "madhya pradesh",
    "మధ్య ప్రదేశ్",
    "bhopal",
    "భోపాల్",
    "maharashtra",
    "మహారాష్ట్ర",
    "mumbai",
    "ముంబై",
    "manipur",
    "మణిపూర్",
    "imphal",
    "ఇంఫాల్",
    "meghalaya",
    "మేఘాలయ",
    "shillong",
    "షిల్లాంగ్",
    "mizoram",
    "మిజోరం",
    "aizawl",
    "ఐజాల్",
    "nagaland",
    "నాగాలాండ్",
    "kohima",
    "కోహిమా",
    "odisha",
    "ఒడిశా",
    "bhubaneswar",
    "భువనేశ్వర్",
    "punjab",
    "పంజాబ్",
    "rajasthan",
    "రాజస్థాన్",
    "jaipur",
    "జైపూర్",
    "sikkim",
    "సిక్కిం",
    "gangtok",
    "గాంగ్‌టక్",
    "tamil nadu",
    "తమిళనాడు",
    "chennai",
    "చెన్నై",
    "tripura",
    "త్రిపుర",
    "agartala",
    "అగర్తల",
    "uttar pradesh",
    "ఉత్తర ప్రదేశ్",
    "lucknow",
    "లక్నో",
    "uttarakhand",
    "ఉత్తరాఖండ్",
    "dehradun",
    "డెహ్రాడూన్",
    "west bengal",
    "పశ్చిమ బెంగాల్",
    "kolkata",
    "కోల్‌కతా",
    // --- Union Territories ---
    "andaman and nicobar islands",
    "అండమాన్ నికోబార్ దీవులు",
    "port blair",
    "పోర్ట్ బ్లెయిర్",
    "dadra and nagar haveli and daman and diu",
    "దాద్రా నగర్ హవేలీ మరియు డామన్ డయ్యూ",
    "daman",
    "డామన్",
    "jammu and kashmir",
    "జమ్మూ కాశ్మీర్",
    "srinagar",
    "శ్రీనగర్",
    "jammu",
    "జమ్మూ",
    "ladakh",
    "లడఖ్",
    "leh",
    "లేహ్",
    "lakshadweep",
    "లక్షద్వీప్",
    "kavaratti",
    "కవరట్టి",
    "delhi",
    "ఢిల్లీ",
    "new delhi",
    "న్యూఢిల్లీ",
    "puducherry",
    "పుదుచ్చేరి",
    "pondicherry",
    "పాండిచ్చేరి",
  ],
   politics: [
    // --- Andhra Pradesh Leaders ---
    "ys jagan mohan reddy", "వైఎస్ జగన్ మోహన్ రెడ్డి",
    "n chandrababu naidu", "ఎన్ చంద్రబాబు నాయుడు",
    "ys rajasekhara reddy", "వైఎస్ రాజశేఖర రెడ్డి",
    "pawan kalyan", "పవన్ కళ్యాణ్",
    "jr ntr", "జూనియర్ ఎన్టీఆర్",
    "y s sharmila", "వైఎస్ షర్మిల",
    "botcha satyanarayana", "బొత్స సత్యనారాయణ",
    "yanamala ramakrishnudu", "యనమల రామకృష్ణుడు",
    "devineni uma", "దేవినేని ఉమ",
    "paritala ravi", "పరితాల రవి",
    "ganta srinivasa rao", "గంటా శ్రీనివాసరావు",

    // --- Telangana Leaders ---
    "kcr", "కేసీఆర్",
    "k chandrashekar rao", "కల్వకుంట్ల చంద్రశేఖరరావు",
    "k t rama rao", "కేటీఆర్", "కె టి రామారావు",
    "harish rao", "హరీష్ రావు",
    "revanth reddy", "రేవంత్ రెడ్డి",
    "asaduddin owaisi", "అసదుద్దీన్ ఒవైసీ",
    "akbaruddin owaisi", "అక్బరుద్దీన్ ఒవైసీ",
    "jana reddy", "జనా రెడ్డి",
    "komatireddy venkat reddy", "కొమటిరెడ్డి వెంకట్ రెడ్డి",
    "etela rajender", "ఈటల రాజేందర్",
    "sabitha indra reddy", "సబితా ఇంద్రారెడ్డి",
    "pocharam srinivas reddy", "పోచారం శ్రీనివాస్ రెడ్డి",
    "tummala nageswara rao", "తుమ్మల నాగేశ్వరరావు",
    "kadiyam srihari", "కడియం శ్రీహరి",

    // --- National Leaders (optional add) ---
    "narendra modi", "నరేంద్ర మోడి",
    "amit shah", "అమిత్ షా",
    "rahul gandhi", "రాహుల్ గాంధీ",
    "sonia gandhi", "సోనియా గాంధీ",
    "priyanka gandhi", "ప్రియాంక గాంధీ",
    "arvind kejriwal", "అర్వింద్ కేజ్రీవాల్",
    "mamata banerjee", "మమతా బెనర్జీ",
    "nitish kumar", "నీతీష్ కుమార్",
    "uddhav thackeray", "ఉద్ధవ్ ಠాక్రే",
    "sharad pawar", "శరద్ పవార్",
  ],
};

export function classifyArticle(text) {
  const lowerText = text.toLowerCase();
  const categories = {};

  for (const [cat, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    let score = 0;
    for (const kw of keywords) {
      if (lowerText.includes(kw)) score += 1;
    }
    if (score > 0) categories[cat] = score;
  }

  let topCategory = null;
  if (Object.keys(categories).length) {
    topCategory = Object.entries(categories).sort((a, b) => b[1] - a[1])[0][0];
  }

  return { categories, topCategory };
}
