name: Auto-approve and merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    if: github.actor == 'dependabot[bot]'
    needs: auto-approve
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PR
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
