name: Update package-lock.json

on:
  pull_request:
    paths:
      - "package.json"

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Commit updated lockfile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "chore: update package-lock.json [auto]" || echo "No changes to commit"
          git push

      - name: Comment on PR
        if: success()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: lockfile-update
          message: |
            ✅ The **package-lock.json** has been updated automatically.
            You can review the changes here:  
            👉 [Files changed](${{ github.event.pull_request.html_url }}/files)
